apiVersion: v1
kind: Secret
metadata:
  name: a2a-bridge-callers
  namespace: agentgateway-system
type: Opaque
stringData:
  matrix-a2a-bridge: ENC[AES256_GCM,data:h8ycRNDAKT4z6HV4d73/Z2Yy9Hv3puk3F1Z3CrqoFMkz3teRdC5GsJgrI4oGhf+9xj9GqfPFxmgWWRUJcPl2piV8Gj1MA9LQExz574pEpGFIaYDuZKzy9zg+rWROvptF0aYP3RNLMHkXTl6cwthRguOZjzmDCBSZUDa0wipu4JoiFaoqC6DZBC8=,iv:Ne1+My1ST0oveGMhRO9YAJbqhY2CTgu769emaglYpk0=,tag:lF8G0UpJZEAsxJEckya5Wg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYb2tib0N3KzFIOEwyVXZh
        ZWlXaE0rT2NnWnVOMFRBK242L2dXc3U2c25nCmcyY0RZdlFzU3JyTUc2MmNwMFVJ
        RC85c0pZOWVtOWE0MEwvRWR0ZDFLTDAKLS0tIEZ1SlJ3WFk0bnhIZkN6eSswUys1
        UzcyTU9VVzh5Sm1XM1RXWDQ0dlNOUjAKxyHzbPdi/TXcnRzj+6ODmB/DEIdc5D88
        QStUVknOaPjZHgx88XMiqid4Zec+koqODZXufyOXoFX5loaUuDWhgg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1nhwmnjct2c7jjes9f7qw45rphzjdvp2meluzzpm3myltaueahg2stefk6e
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-11T13:44:48Z"
  mac: ENC[AES256_GCM,data:3myb47Cnx//0eUfZK1DNC1bg1z5OxK85DLn/wm5PpPuJQSVIPE0oe6piTBeu2hns3gtNiy5lcSIiMvLipU7mV84i0+vmfgjZDTRfqiS3ii4vuGrWN/7TY6pPHWvMLbnVAYTSySG4/wLSivesI82QEG81d3/RlWrGF7gRU2U4M04=,iv:2dakItECKvJ7kvbUAkFWmgvtguoHHHd0Dmb8dMILRH4=,tag:aM15+FRhPwxNz9H6SMchBA==,type:str]
  version: 3.13.2
---
apiVersion: v1
kind: Secret
metadata:
  name: a2a-bridge-credential
  namespace: bridge
type: Opaque
stringData:
  token: ENC[AES256_GCM,data:WtgJdG99+kvmWK5LNwipzVoP6MLEXivi9XktehUcKamZDxIWNsS9n8+mykNNmpjCaL/3HCDRp6CXXJR6xr/sVQ==,iv:37x3vLN/HFbKHtP3jK2NAxasj87GhV/zqHMyAldstM4=,tag:xiOdDBr9qmHK/DnvIbMggg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYb2tib0N3KzFIOEwyVXZh
        ZWlXaE0rT2NnWnVOMFRBK242L2dXc3U2c25nCmcyY0RZdlFzU3JyTUc2MmNwMFVJ
        RC85c0pZOWVtOWE0MEwvRWR0ZDFLTDAKLS0tIEZ1SlJ3WFk0bnhIZkN6eSswUys1
        UzcyTU9VVzh5Sm1XM1RXWDQ0dlNOUjAKxyHzbPdi/TXcnRzj+6ODmB/DEIdc5D88
        QStUVknOaPjZHgx88XMiqid4Zec+koqODZXufyOXoFX5loaUuDWhgg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1nhwmnjct2c7jjes9f7qw45rphzjdvp2meluzzpm3myltaueahg2stefk6e
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-11T13:44:48Z"
  mac: ENC[AES256_GCM,data:3myb47Cnx//0eUfZK1DNC1bg1z5OxK85DLn/wm5PpPuJQSVIPE0oe6piTBeu2hns3gtNiy5lcSIiMvLipU7mV84i0+vmfgjZDTRfqiS3ii4vuGrWN/7TY6pPHWvMLbnVAYTSySG4/wLSivesI82QEG81d3/RlWrGF7gRU2U4M04=,iv:2dakItECKvJ7kvbUAkFWmgvtguoHHHd0Dmb8dMILRH4=,tag:aM15+FRhPwxNz9H6SMchBA==,type:str]
  version: 3.13.2
