apiVersion: v1
kind: Secret
metadata:
  name: model-secret
  namespace: agentgateway-system
type: Opaque
stringData:
  Authorization: ENC[AES256_GCM,data:j5UtwdDZEM47Z52rwagl6dzigg==,iv:2PslDXMJ6XgJAATJMzNum5BdQYdfopYOUi7988cypP8=,tag:YHyJoK9f2tNyORtmHWQLBg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaelFka3NjL3ZmK0lJZWF3
        VTc3aGFtaXdmdXlZSXg2RndHbDMyWWlScEhBCkNuTTN4OG91L3hXQnk0NjgycW5T
        U1MxZVhpaklDR3QvOFpPbDVRVEN0RU0KLS0tIFdMM1kvSHd1RGhMbU4zTksyeURR
        YUxZUVZzNU1FTUFwVEZkMEhTc3A1UVEKUU6PnvVvToS8nvZI5w4F54EHnGWs6jXm
        ajlzRpHQA+Zww2k4G5/cESVyHNvA97W9KdxnKw3sMQROnyL7jWgEtA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1nhwmnjct2c7jjes9f7qw45rphzjdvp2meluzzpm3myltaueahg2stefk6e
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-10T12:51:06Z"
  mac: ENC[AES256_GCM,data:bmWRQJL+Z1bZaSAf2NmwtClaYlZdX7rLVyzZQLw303cXhFNFyizN7zSAPDVCZOw1l5j1brLrYQRtxKTBc8abDwkdktJn7gKbXftYJX/QUYLvIuxPNb0BId4FwvbmJNm6ZWJb8JXyZ2ScAXEmnZ678gYK8qiGDLbT7n+4ghsCSqo=,iv:pepGzeEYn+bcGgLdEHdalqtm+Qx4BmlMXBTS4AeEYSE=,tag:1mUMOKV46wKE3WGB9VNIVg==,type:str]
  version: 3.13.2
