apiVersion: v1
kind: Secret
metadata:
  name: kagent-db
  namespace: kagent
type: Opaque
stringData:
  url: ENC[AES256_GCM,data:Ax68SAUuIerChbogq7dAJ/EediVpGb7rkPFYbUyk+tpfsEguUcdjNNVw+pqoBdVmdJPyhD8vbw/rusk1liKhmuTPfuZm2DSEWuhW3p9CjmB540Yo8VGCGc11lyHWqbWD85r+yn7OC0avdwMPIiWCAXQcAaCz/DzMO0NVmXPOXm36vw0iCbm4aJcR,iv:Uyb7xY7Fd5Lf778iscLll3jzWArTV9qP7e68feFdrbM=,tag:AJjhomMXZwRFjYZlreS6/g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRVy9JTFB5Z0hNN0U2MlR0
        U3AvVVI1TnRkZXBuaUJKS3kxZHdqU1F1R1V3CkJyRmVzdmNhdTVjVjlrRHVLTXpv
        T3prejhLTFVYWUNNeWFCVjl5MGM0SHcKLS0tIDRXYXZxN2FxQldKVEs4NzNzREd4
        dm82elFheHp2MTJ1djVlcXRiUHF1MlEKHOZBRekR933Xv+Ws5gdI11TFl7ebpWCg
        xiifHkUQpzBGdD3sc2OiHM0Eu1Ysyy8cSjLSLXYkPXJEOi/KeKMDTg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1nhwmnjct2c7jjes9f7qw45rphzjdvp2meluzzpm3myltaueahg2stefk6e
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-10T12:51:06Z"
  mac: ENC[AES256_GCM,data:XTSGxcT9g3CeR55/OcYAwiP8roWehbtIhmaVjQ9ym9cuemZFYie3GpHACp0UWwpwS8J8NWFwLmHLwzBp42HcZTmq0fnIjhCfsAjQdJWVozKJdNx9fQ9N3tjhBlHi2uh395cwMlhdezbbDRKPjzUsUFUFTaYTZU/zo6XYzRxJzG4=,iv:7HCyVJnrdkC7VxV7yiSjnVgrlD3tgguDgVbZzaIKiHo=,tag:jPbMFmM5Pw2/wM+irZv9+Q==,type:str]
  version: 3.13.2
---
apiVersion: v1
kind: Secret
metadata:
  name: kagent-model-auth
  namespace: kagent
type: Opaque
stringData:
  OPENAI_API_KEY: ENC[AES256_GCM,data:HcIfDyH7Cl+oRLz/oGg0NULpdua6kLq43sr5qbRg0lWkwlh2w+X8C5LI7A==,iv:cGIVUP0t/OeIZTIf5wgDOhAHJQxpq3oyMuLrV6tRXhE=,tag:Xrbm53SOeLVZLDRzq+FHTA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRVy9JTFB5Z0hNN0U2MlR0
        U3AvVVI1TnRkZXBuaUJKS3kxZHdqU1F1R1V3CkJyRmVzdmNhdTVjVjlrRHVLTXpv
        T3prejhLTFVYWUNNeWFCVjl5MGM0SHcKLS0tIDRXYXZxN2FxQldKVEs4NzNzREd4
        dm82elFheHp2MTJ1djVlcXRiUHF1MlEKHOZBRekR933Xv+Ws5gdI11TFl7ebpWCg
        xiifHkUQpzBGdD3sc2OiHM0Eu1Ysyy8cSjLSLXYkPXJEOi/KeKMDTg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1nhwmnjct2c7jjes9f7qw45rphzjdvp2meluzzpm3myltaueahg2stefk6e
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-10T12:51:06Z"
  mac: ENC[AES256_GCM,data:XTSGxcT9g3CeR55/OcYAwiP8roWehbtIhmaVjQ9ym9cuemZFYie3GpHACp0UWwpwS8J8NWFwLmHLwzBp42HcZTmq0fnIjhCfsAjQdJWVozKJdNx9fQ9N3tjhBlHi2uh395cwMlhdezbbDRKPjzUsUFUFTaYTZU/zo6XYzRxJzG4=,iv:7HCyVJnrdkC7VxV7yiSjnVgrlD3tgguDgVbZzaIKiHo=,tag:jPbMFmM5Pw2/wM+irZv9+Q==,type:str]
  version: 3.13.2
