apiVersion: v1
kind: Secret
metadata:
    name: pg-keycloak
    namespace: postgres
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:OSjKxAKa7qk=,iv:ca7fuDLIVr6vwdsLBegv1nO4NJGz8qPZm+6dWz9MZoI=,tag:w0ZihMYukF0sTsJGdxwTkw==,type:str]
    password: ENC[AES256_GCM,data:6bZr72KYUTi9ktntNZy/4MkSyyFkc2Vd4qt1egdE2u+2kuXEjMXEC5qOpRLuUo6/,iv:6UykZsmorHDUFZibM8wCKM+VSY+v846vws7yZN8uBGI=,tag:ZF6XPLQHf/gxg/xbMEPhdA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkTXMvTXptMUQzT2tCSXUz
            VjNINEl4bjBSekVtendZSmdTMHdURHNvOWdZCld5MXFmcSs2Tk0ySDR6SU1SMmNY
            RjdEbXJobXd1bGplZ204UGk4MHhHQTgKLS0tIHpmWERZRlBVNnpqays5bW1kczJi
            M1ljc3NpZGhvQkpEcG40RWJEMTlnMmcKS8MIe4KJ8iYfAojst/y4Y3+iHs6ikQxp
            xeSiDnOzs5VSxdn7yx6LoYb86XDrGB/hoLftJfYTPH4Ltyi4xAJhKw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhwmnjct2c7jjes9f7qw45rphzjdvp2meluzzpm3myltaueahg2stefk6e
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-12T15:27:44Z"
    mac: ENC[AES256_GCM,data:4P/3hM7xSMqWH2C6Bq8ZDsiJ+oRkhPwwMsTlHvf8JF6ymdIBwAdf0A7eVHpkxFIalLNi86Hxi51Ctdjrp0vTQCGzSGl9SJJPUwy+1JJ548kJwSU0KXFtV9p39URnpIJuYsoxUee2yf/r3YXxvWDEKTOy6VFDitXNCmrfFYwqqsI=,iv:RXCPxqRVgM7N5OFwrTJHjvnPRK55rTC+8MhlEZU1tvU=,tag:Yh36AcvH/O5UEa3JQQsAlQ==,type:str]
    version: 3.13.2
---
apiVersion: v1
kind: Secret
metadata:
    name: pg-keycloak
    namespace: keycloak
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:8YxPsWnTKbQ=,iv:9v2GHPd4uy0jF37nUV6RQ7zCjCvRcbM0c0fPS0S97oY=,tag:At936APCvDJyhhY5t5YsoA==,type:str]
    password: ENC[AES256_GCM,data:zYRkXpn7lK7oEHOvnsImqVTEwps6JwnItc1ekf9DHF1FQtDw+sF5e0pB0Min2lFz,iv:x8N3pA2MUqEFUxiqFH/8s1xWI95TEjxctNiqx9MI+EY=,tag:4DoMzZC76RcxXvwFOIeYfQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkTXMvTXptMUQzT2tCSXUz
            VjNINEl4bjBSekVtendZSmdTMHdURHNvOWdZCld5MXFmcSs2Tk0ySDR6SU1SMmNY
            RjdEbXJobXd1bGplZ204UGk4MHhHQTgKLS0tIHpmWERZRlBVNnpqays5bW1kczJi
            M1ljc3NpZGhvQkpEcG40RWJEMTlnMmcKS8MIe4KJ8iYfAojst/y4Y3+iHs6ikQxp
            xeSiDnOzs5VSxdn7yx6LoYb86XDrGB/hoLftJfYTPH4Ltyi4xAJhKw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhwmnjct2c7jjes9f7qw45rphzjdvp2meluzzpm3myltaueahg2stefk6e
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-12T15:27:44Z"
    mac: ENC[AES256_GCM,data:4P/3hM7xSMqWH2C6Bq8ZDsiJ+oRkhPwwMsTlHvf8JF6ymdIBwAdf0A7eVHpkxFIalLNi86Hxi51Ctdjrp0vTQCGzSGl9SJJPUwy+1JJ548kJwSU0KXFtV9p39URnpIJuYsoxUee2yf/r3YXxvWDEKTOy6VFDitXNCmrfFYwqqsI=,iv:RXCPxqRVgM7N5OFwrTJHjvnPRK55rTC+8MhlEZU1tvU=,tag:Yh36AcvH/O5UEa3JQQsAlQ==,type:str]
    version: 3.13.2
