apiVersion: v1
kind: Secret
metadata:
    name: pg-knowledge-owner
    namespace: postgres
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:uLW7jRkL5yuLdNlKf9eG,iv:CWajpnzArrbKq1aJwLXvI4m8tlMhZgGXfOFvQve9KiE=,tag:hzwDGQIPhuTwb2vSi4S54w==,type:str]
    password: ENC[AES256_GCM,data:KFzF/MuTb8gkXYhev6aTFPXdd1Fi51LcTHr2IkwEPqR4Gmb6pft5Rx3w9LSvkT/X,iv:gPojTqv44zLdKaoxu5Aaw3Is/0fB1VdHRXwIPq9Tbhw=,tag:KoR/BVh1Ols+JDWQE4x1Uw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwdjlDSmV2cSt6ZEtIVUdT
            d0lISVBrTWRiQTFHcjJ1aEtiNmV4RGV1RFV3CmxYV2FVZFl3OHlnNmVLanUva0NM
            OUFiVlFpY1I4U2YvcnA4L2tkLzhZWTQKLS0tIGc5Nmpjd1FYbTNVU1kvQk1DaDF3
            RUtOdHFqVUVTckxYSm9iSUl4eUxnQ0kKGfXDdCdqoGbS+Sld1YVr+qVrVTs+Lbg8
            3UuaDz8XiccY7eujz8mHW8G+p4iLtomqibxw0aiPulrvRoM2rTj8og==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhwmnjct2c7jjes9f7qw45rphzjdvp2meluzzpm3myltaueahg2stefk6e
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-15T17:04:47Z"
    mac: ENC[AES256_GCM,data:am+2ZOv+v9kpGC8bOjHnnl9er2S0LzZj8xrplPH0b3XScS2Rp4jNYbLiXHR0pfCoZWxUBfIkpU5srYEoavU5MiB2W76siJVpWzWG18rRVXY4SxlS770NHXaQPk/WLfXWuhkYfwXWrjftoEhoKVFM6+eKK/Qe5LypiTkkCC6OvYw=,iv:lF6on2lRAOpRjvjKFZMip3abVorhURFX+k9j14HbL48=,tag:tCwDS6jAqby36710k61SiQ==,type:str]
    version: 3.13.2
---
apiVersion: v1
kind: Secret
metadata:
    name: pg-knowledge-retrieval
    namespace: postgres
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:1HwhN2bwPL1r7HMqcBRzXcKphQ==,iv:/JDx1O1E4SPou3P3hFWcHZ9zeM0Bxa/cixg/Con1HV8=,tag:s9n6q+26Q0IW7WrFstzZiQ==,type:str]
    password: ENC[AES256_GCM,data:dvQEZtxA5c4OiPnotCe7kw0tzBZjjHFIF2lUX6rni+ScH242HaomWHTdJ6eNjnFu,iv:EaTR2M4fqLkYRqWIAaAUJ0S8VOnV9fKilhYowoHaqV0=,tag:HfwnfrYa26V1tv4bIgp8Qw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwdjlDSmV2cSt6ZEtIVUdT
            d0lISVBrTWRiQTFHcjJ1aEtiNmV4RGV1RFV3CmxYV2FVZFl3OHlnNmVLanUva0NM
            OUFiVlFpY1I4U2YvcnA4L2tkLzhZWTQKLS0tIGc5Nmpjd1FYbTNVU1kvQk1DaDF3
            RUtOdHFqVUVTckxYSm9iSUl4eUxnQ0kKGfXDdCdqoGbS+Sld1YVr+qVrVTs+Lbg8
            3UuaDz8XiccY7eujz8mHW8G+p4iLtomqibxw0aiPulrvRoM2rTj8og==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhwmnjct2c7jjes9f7qw45rphzjdvp2meluzzpm3myltaueahg2stefk6e
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-15T17:04:47Z"
    mac: ENC[AES256_GCM,data:am+2ZOv+v9kpGC8bOjHnnl9er2S0LzZj8xrplPH0b3XScS2Rp4jNYbLiXHR0pfCoZWxUBfIkpU5srYEoavU5MiB2W76siJVpWzWG18rRVXY4SxlS770NHXaQPk/WLfXWuhkYfwXWrjftoEhoKVFM6+eKK/Qe5LypiTkkCC6OvYw=,iv:lF6on2lRAOpRjvjKFZMip3abVorhURFX+k9j14HbL48=,tag:tCwDS6jAqby36710k61SiQ==,type:str]
    version: 3.13.2
---
apiVersion: v1
kind: Secret
metadata:
    name: pg-knowledge-retrieval
    namespace: knowledge
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:Nd1nK2CyI1KJ9v7VzJYmM6VEPg==,iv:KQqfOIutShUPTrmn3GfHz0MxJuo2VXgz29Ydl1E5nMw=,tag:pRY6J1U6IkbZd0zYmIrhbw==,type:str]
    password: ENC[AES256_GCM,data:EUG98GBqXutDESn/bie+Is85ppjGG651FCMjdh102KaYcY/JhKSWRwJYPoMAg3xc,iv:xJp6VbW20v7iUsKMEGcfk5Cg6grpMnjSYD/t2NPnomo=,tag:YmK/WaXgp2A+tUrLQJW7Pw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwdjlDSmV2cSt6ZEtIVUdT
            d0lISVBrTWRiQTFHcjJ1aEtiNmV4RGV1RFV3CmxYV2FVZFl3OHlnNmVLanUva0NM
            OUFiVlFpY1I4U2YvcnA4L2tkLzhZWTQKLS0tIGc5Nmpjd1FYbTNVU1kvQk1DaDF3
            RUtOdHFqVUVTckxYSm9iSUl4eUxnQ0kKGfXDdCdqoGbS+Sld1YVr+qVrVTs+Lbg8
            3UuaDz8XiccY7eujz8mHW8G+p4iLtomqibxw0aiPulrvRoM2rTj8og==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhwmnjct2c7jjes9f7qw45rphzjdvp2meluzzpm3myltaueahg2stefk6e
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-15T17:04:47Z"
    mac: ENC[AES256_GCM,data:am+2ZOv+v9kpGC8bOjHnnl9er2S0LzZj8xrplPH0b3XScS2Rp4jNYbLiXHR0pfCoZWxUBfIkpU5srYEoavU5MiB2W76siJVpWzWG18rRVXY4SxlS770NHXaQPk/WLfXWuhkYfwXWrjftoEhoKVFM6+eKK/Qe5LypiTkkCC6OvYw=,iv:lF6on2lRAOpRjvjKFZMip3abVorhURFX+k9j14HbL48=,tag:tCwDS6jAqby36710k61SiQ==,type:str]
    version: 3.13.2
