apiVersion: v1
kind: Secret
metadata:
  name: matrix-a2a-bridge-db
  namespace: bridge
type: Opaque
stringData:
  url: ENC[AES256_GCM,data:PyzAgYbq/7lq8fF843ZL3u2bmL9C2Payes3v09oQbTyHb2lLpCfUlL4vKHjIC3Uky1zChm4M07vf/fUYdJfAPMq/6qWNAauXFCQcJbU21wttRbjGrc8E4GHNzw1W+XRUeTcInL8c/YIDRU1+mfSn/VrzF9BWgO9ahvjiPH/taGAUozrMCydQZg==,iv:riFzAqYgBCN+fw68p3w0zaIM0BROoDCE4AxAfeaw2tk=,tag:OMr4nlNdzfOGeY1owsBClQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiOWpJd2dVZUpyK1pDZWJO
        NGhibFV4MWl1T0FBQjRzdDhmMXFoNE5JTHpjCkJUM3kvYjU2RkhORWdYS2huWnpE
        dXVFVDZTVWRnT2R5Q3NhRzdEZGcxSVEKLS0tIFF3LzFWeGt2TENnODVPMWkxelUx
        eHN4OGpBWXpnTmIzWWozTlAxazRnT0EK14IqXlebmBB5YrRyMaIWeN2W4M5uF58V
        8g9umVEcj8SoupIBd6dNc0XCB48pCwkV5qxHR49TXs3SPxyzRgXFfg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1nhwmnjct2c7jjes9f7qw45rphzjdvp2meluzzpm3myltaueahg2stefk6e
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-10T12:51:06Z"
  mac: ENC[AES256_GCM,data:rItp0Uu38Q3MmHT0eAS6cbxnj8PTBr3KBmQgTnsGqPboySDfbn1ayNoVbzopMJ1i+j2KgP6/beSyFFZQJXrvb/FT/XKIwQrMCNmVbXKMTF1VP+G+pmIP9ELotgYltLtctM6CXzqkQELMXsATxlkfnGN3iZrI/IkE0MhIht1nVUg=,iv:b4IjAKs0k9Lvb1lMgqRlkwTlVacdOz7UYUFIFqqU1UM=,tag:ZUVG+BGByRpmWKP68snpjg==,type:str]
  version: 3.13.2
