apiVersion: v1
kind: Secret
metadata:
  name: matrix-a2a-bridge-registration
  namespace: bridge
type: Opaque
stringData:
  registration.yaml: ENC[AES256_GCM,data:z6QnmYE6kgbt5VTxjcu7VWl1nCOWUJlE64HquKkZUER83j3/DSsKoP04N9bRE3JGm2MCc+/kJ0tClS+9OhUNsgIXXYSC5hvTZtuuz0jVNIFdxtrg8g1pxnm5JsdGvVv4OBC7L2blEhJngFztvI4Li6TwMOJNjOOyIzYSS/CqHp2q3v3k5zCQKEPIUzSQxRrA+mXD4S/mM+Xepdz/ktbIyNI8vxcPXkO2bPkmqFb0anOO7NbaNEsW8uRltdJq2eqqHopdQnqzz/QCIMD9psAA4i582Ysh2gxl3FCRek74vTbgEJ9ZaCxZOST1kF4Ty45tA9qQOVsLMvlZi0SesmJs+heJUVCkYKPh3BynubIfeZ2xPLqtajG4yJm4EUfp1WdNHWmK1bmcJw9EpSvYbe8XzxkO66L2RC4twYLetBntMXWV/zc2nY3wEjrz7SESJbiuOL4+hOX9I+ixF+1saqMtcyZT/tzAQtc6GmHDgm/yAiXtZWrKsdVUkfn+8M8Uyhhx36VTOm0oR/qJ+BhkU0/XdoqDXzmu3zSzZUm+YsEhrmOPmlz3qWFxUO0+WBjWDB0OJYZVRO0=,iv:BacI17X8IecGRQ5nHG/L0IIQeiRgX1PzoWaGmvgW+Yc=,tag:Hztaz6ajxDcCYH8lKEZonQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvdXpFUWorQmNtT2Y2YWZq
        b1I3Z0VaSjdmVUdiemp3S1FTcFlDenNyMUgwCjIxSVo4ejJBU21tSjRqd09oZTV4
        ZFBNOUxaTFZXeTZqeExiWFY1OHFabUUKLS0tIFJEWGkxN0RYTmxyWWFSbmZQOWRU
        Sy9BbmRzYm1hUmJIWWZsNFpmZFVTVmsKCHraYa6PLstsAFNq7GYyQRhABmKL5VWI
        ZCULsKefxNacW+Q9Y2P8KFskphIhEm3eLP9RoYJMrEasxU4u2Un7Wg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1nhwmnjct2c7jjes9f7qw45rphzjdvp2meluzzpm3myltaueahg2stefk6e
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-10T12:51:06Z"
  mac: ENC[AES256_GCM,data:IIPxuVwCDCiHKQ1g2aIRTdJVbrDyriXW6SvPTgJ8D8wSl8k9k5h+Ipg+8jiI61p7dFjb54fzOcbhR6no9DWvhuLW8z4qW/PGEShsBxTxeCbyeCmT8EYaY456MUsMT6At7MyeKMXfVygZvHmrGp8vQIhxgWsc8HLqESWgJTwyqG4=,iv:j0E4Siob46ITqwYnyD40ctInN8wPFsfzVq8EsheC0bs=,tag:11YhgWsvSjCmJMioc5VKmw==,type:str]
  version: 3.13.2
---
apiVersion: v1
kind: Secret
metadata:
  name: matrix-a2a-bridge-registration
  namespace: matrix
type: Opaque
stringData:
  registration.yaml: ENC[AES256_GCM,data:A/kWHhzjIHXce5jA9BJ0153/pUJ5/nFJY8xoCJoiWG2SEOIpvTvBf7UMXpAg1twgpfjDwmf/vOeu24kLwmca9hQjTmlZMEKxVrq3XBFp3dl0KwsSJg9qXskni5Yu3HKIeXpTvEfg6YNiyxHHw90xs4Vso8cofo7FQeT+RLZYNWYZLj7cUTEyQGHyL0hmvi2gPQSYyZAADpCGaWcHbo5QQknx4uBMDyxH4n7Gohdx1tE6oelsPVjBqqdv39Wg7VF526dnTjXAve/s7Z423bL3nkBWl2m4jYlqno3ZdyRUmKWYibsgVOz97diyGtreP2Qij8Jzm5IoWh1KTNAfUkKpbfTONN9do/lui3+ViH5zCHSbbP4DdZFtAiitQpU4bu3pDfQcUo4+0FWwC80ya4yGfSO62Hwc1RzjdmoQKAiutUZzvuzXZHWWx3zg0AzoLlAmpJ6PEym4+HsgYt1uWUvMRo5NuZKgZFas9R23Ro8+O3IOSaSQaTn6NT3TR/Sd7mFzUx0tK8dH38hq262hF9zHA98pTH/jGereke2cWwNBEX1RnowNKQgFwOxttFjvMey/yMnLvc4=,iv:WcCTiycYt7lhut8ET3TnnNJdRQbAIFcc66R//JfNK9w=,tag:seeKen4824IhZKS12W2X/Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvdXpFUWorQmNtT2Y2YWZq
        b1I3Z0VaSjdmVUdiemp3S1FTcFlDenNyMUgwCjIxSVo4ejJBU21tSjRqd09oZTV4
        ZFBNOUxaTFZXeTZqeExiWFY1OHFabUUKLS0tIFJEWGkxN0RYTmxyWWFSbmZQOWRU
        Sy9BbmRzYm1hUmJIWWZsNFpmZFVTVmsKCHraYa6PLstsAFNq7GYyQRhABmKL5VWI
        ZCULsKefxNacW+Q9Y2P8KFskphIhEm3eLP9RoYJMrEasxU4u2Un7Wg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1nhwmnjct2c7jjes9f7qw45rphzjdvp2meluzzpm3myltaueahg2stefk6e
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-10T12:51:06Z"
  mac: ENC[AES256_GCM,data:IIPxuVwCDCiHKQ1g2aIRTdJVbrDyriXW6SvPTgJ8D8wSl8k9k5h+Ipg+8jiI61p7dFjb54fzOcbhR6no9DWvhuLW8z4qW/PGEShsBxTxeCbyeCmT8EYaY456MUsMT6At7MyeKMXfVygZvHmrGp8vQIhxgWsc8HLqESWgJTwyqG4=,iv:j0E4Siob46ITqwYnyD40ctInN8wPFsfzVq8EsheC0bs=,tag:11YhgWsvSjCmJMioc5VKmw==,type:str]
  version: 3.13.2
