apiVersion: v1
kind: Secret
metadata:
    name: pg-slackbridge
    namespace: postgres
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:4DmmYU07zDN3hTE=,iv:Jbc7dIMAhmOwRFJQFWWxStQgy7Pwj7N3uyroZdnJlOk=,tag:rcz/K9fZHwy5nOJXk1p28A==,type:str]
    password: ENC[AES256_GCM,data:Ezi/IyyMvbzSmQwQ5ISkL7s1PLJ6k+6CEV0z3hUq1yHNBhF5nfYfhaTkrwqGkXAZ,iv:0rnwu3W0WbPJsPqzbq7u9avsizjsRnU13p+RbIDMKYA=,tag:f7+U4xXRdzP53bnwtX9K0Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZbndTSjJETWRZREZtUkJL
            UXBvSGVNYUFjUEJESjVNS1Azcjl6MEU2b0VBCkhZZjhXSW85MmkyYjczVVllam9V
            a1E2WklHQi9HaG15bTh3QmxvdkZTVFUKLS0tIERwTEtFczUvWWtUaW9aRFNuaFBq
            NjZLNEtrMmdDRzEyOWY0UFJqQUk2WmsKNDhWsOElPYYi3CmHDlJstB/HPa/eMJy0
            pgacEHKgaafuWbrhcev5jdFLR1KeJyvEL1AhderZA9XbGbMi/O4xHw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhwmnjct2c7jjes9f7qw45rphzjdvp2meluzzpm3myltaueahg2stefk6e
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-11T15:36:33Z"
    mac: ENC[AES256_GCM,data:BrqKwoXyhmDOMCr1QYtN/4ERx4QqSyyrw8gurmeK5xbANhtrv7WPeG6z2LBDp8uzqtG0kqF2uWuAsEhZ1Dugn0suwsTfek7PmONN5Uyqta8UAGBwa54QdryddMwjItG+d0FWr3Nfu0VZZvul14+KCobMW4YRW47vn/Z/svrB7Eg=,iv:MUV1FQNp37wQYSRdwTVQl+y/jwM4UIfS5ReFeC75Jxk=,tag:lEPuidqENbxgRMMqAdVfzg==,type:str]
    version: 3.13.2
---
apiVersion: v1
kind: Secret
metadata:
    name: mautrix-slack
    namespace: bridges
type: Opaque
stringData:
    database-uri: ENC[AES256_GCM,data:Zi2ES5IQROePrY5KyxtAoLwY78cHrgsL8SRLzjF6A0TBfQNPUzZ523xt7pUznT337XWB5rVVLAtLA0ni+iXo7w5MZ/Wv1jS17JLXSMuLJDQ1YlNouVYmetr1uqsKTn2drzoQnvamPncole2AbrtsbV7MpakncDUXDXY8d8gGcNn2+VFVWbloBDvlWpJfcNjt564=,iv:Ia/X856F4puHDVJemRWXT3eLC/YstWMAdF2XieLG2Gs=,tag:OeLBRx0UFKzuTcvPRi74lQ==,type:str]
    as-token: ENC[AES256_GCM,data:LBOvprbh+Ve1Vtlm/W6Q5W9nBNiNbySlEW+wgcg3frG3jRu78rJIfC8VKeq5MT6eOtUqhZDjaXakGnIRYdPXfw==,iv:3PtbzIqeZr6R+iQh4RAy95R9rged8s6nbRxK+Zu3720=,tag:8WvvMQ3wAeExasCI/WTWJw==,type:str]
    hs-token: ENC[AES256_GCM,data:ZAlr7euPL7SvmoF91ZxTrNBPg7uRxTp6Ybh37co8a/YIox1KTND3xd/5Q+5Iuejh9Hn/xhqYwm5gcuxwh4wBBQ==,iv:HogkEUlW54cpK2jmnfryzYWxsKuGHDL3Natyyfd/FGk=,tag:dVb51eFTQJ4F1osQfHzmtA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZbndTSjJETWRZREZtUkJL
            UXBvSGVNYUFjUEJESjVNS1Azcjl6MEU2b0VBCkhZZjhXSW85MmkyYjczVVllam9V
            a1E2WklHQi9HaG15bTh3QmxvdkZTVFUKLS0tIERwTEtFczUvWWtUaW9aRFNuaFBq
            NjZLNEtrMmdDRzEyOWY0UFJqQUk2WmsKNDhWsOElPYYi3CmHDlJstB/HPa/eMJy0
            pgacEHKgaafuWbrhcev5jdFLR1KeJyvEL1AhderZA9XbGbMi/O4xHw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhwmnjct2c7jjes9f7qw45rphzjdvp2meluzzpm3myltaueahg2stefk6e
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-11T15:36:33Z"
    mac: ENC[AES256_GCM,data:BrqKwoXyhmDOMCr1QYtN/4ERx4QqSyyrw8gurmeK5xbANhtrv7WPeG6z2LBDp8uzqtG0kqF2uWuAsEhZ1Dugn0suwsTfek7PmONN5Uyqta8UAGBwa54QdryddMwjItG+d0FWr3Nfu0VZZvul14+KCobMW4YRW47vn/Z/svrB7Eg=,iv:MUV1FQNp37wQYSRdwTVQl+y/jwM4UIfS5ReFeC75Jxk=,tag:lEPuidqENbxgRMMqAdVfzg==,type:str]
    version: 3.13.2
---
apiVersion: v1
kind: Secret
metadata:
    name: mautrix-slack-registration
    namespace: matrix
type: Opaque
stringData:
    registration.yaml: ENC[AES256_GCM,data:+wElzFZ2gyTBsZFN5Ph6ILKfkMyM0R/y/E7ZFdRlWL6GIzQRgbuDJdwJ0H+JD/aGVWNYooSwy5hN49LJhPZqhrKRA8gSGNTle1/1diMhskN2CyArk2ne6mUdfT01H2WzfT6GKQEPMpEV++jad5g580wkb0UX+ExcUxrgnnWN4xLgKUDqthA9+KIaRAg63UWynKMgKSkEikTIjO5AIWYVH2gNNf8srcjuhQi5+0/wuD3Zu1AFmQiW+kHciB1aSAHXoW/Qns3RIkq6fvSyxbbmmAv0l7W84FTgwoXfVqNgjeTsGBYZe2yHLvY3rR6M1IVDqx0g5CUatSdQNg7ZNFK2NvDk9aEu+Jxnnra5l0KWTfSGkVgnpD1euNojssHYCmW4NfAwkW2qWy4q3UN2wDbCUezwL4KgN6c1/ysIApjxOtypG1vwGIeco4X9avOFMzum8K+WZ5q0kDv6VFZFyhEi6N1sp45RXbmmDn1pl8d5cQKM4FxAH/FFJQ4fAmdhvMBNRsEsE/yqnIKzlABH3Jc+R8m97k2AxPqXZlAgHgQKxsXpyx2IqqFUCgxe1F9zgVTksNjh5zdMEIGIdT3Tjwfc0fGghKHMyd4WtqQeo14FoJq0rnVc2n9JtXNeK4MpuBkuwKo2ZZj1oKvajhKhydZZ9sokZUPASk0LO8D9,iv:sF4uPpqSH8JG3h0BpdwDY6XHBcS9D5uBqTbVUohdXP4=,tag:CgKdBkFMPi0WDmWdTC0NdQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZbndTSjJETWRZREZtUkJL
            UXBvSGVNYUFjUEJESjVNS1Azcjl6MEU2b0VBCkhZZjhXSW85MmkyYjczVVllam9V
            a1E2WklHQi9HaG15bTh3QmxvdkZTVFUKLS0tIERwTEtFczUvWWtUaW9aRFNuaFBq
            NjZLNEtrMmdDRzEyOWY0UFJqQUk2WmsKNDhWsOElPYYi3CmHDlJstB/HPa/eMJy0
            pgacEHKgaafuWbrhcev5jdFLR1KeJyvEL1AhderZA9XbGbMi/O4xHw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhwmnjct2c7jjes9f7qw45rphzjdvp2meluzzpm3myltaueahg2stefk6e
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-11T15:36:33Z"
    mac: ENC[AES256_GCM,data:BrqKwoXyhmDOMCr1QYtN/4ERx4QqSyyrw8gurmeK5xbANhtrv7WPeG6z2LBDp8uzqtG0kqF2uWuAsEhZ1Dugn0suwsTfek7PmONN5Uyqta8UAGBwa54QdryddMwjItG+d0FWr3Nfu0VZZvul14+KCobMW4YRW47vn/Z/svrB7Eg=,iv:MUV1FQNp37wQYSRdwTVQl+y/jwM4UIfS5ReFeC75Jxk=,tag:lEPuidqENbxgRMMqAdVfzg==,type:str]
    version: 3.13.2
