apiVersion: v1
kind: Secret
metadata:
  name: mcp-agent-callers
  namespace: agentgateway-system
type: Opaque
stringData:
  platform-helper: ENC[AES256_GCM,data:alH7PwdKAMugDafIzoxxP/t5vCImkEZ1exQjhG9TKYpUtb3DKm18a4HrHqJPmB76NMSl16+ARYwvnBoxQtJ8aPSXD7PqNQQVtgXGxD/3wqsaaCpsBN/DZbL3x3OCkxs/lh/rUv5XFbrk+5SY6G8o5UFCI0+iIBXkMmA4BA2sAhIcwLmu,iv:yy3Vfn/tA13RQ6zXU047ibW/BYt2LZrdqibPB2URzIY=,tag:Qhqp9KDf/gRY4tqR7efVzQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByekVWZXhNa3NsbHplaWox
        TFBWN2xjQ25GZWM2RkVFbzcycGh5NDBPNzNNCkxZRUN6dTZSamp5WGpOR1gxbkpE
        ekRsdG9WRGs1Q3hGVitvTFVDNmNnWTQKLS0tIGlmdVNHQzBXQmZCK2JvSGtDVk14
        WHNCQVRBNG1zQkYvVHRZOG9JR3kzUDQKcUttgfuSy0r5bOJQ1s3wNbg6QivbnYSF
        VusuitZN+BKMI9UhmyBkrY+SQrqh8A0E778TFpXZ5nsffPiaJCrMhg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1nhwmnjct2c7jjes9f7qw45rphzjdvp2meluzzpm3myltaueahg2stefk6e
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-11T13:41:56Z"
  mac: ENC[AES256_GCM,data:7xs9MeCYVBtpHrdVCbpgt7izMJR8k0nSDxGfCM9HH+xlfidntPQ5liDcBSM17q2jfcEni60UBcJRjSzUoupiegM4uI/ZsauUMEsnzX+iZlBjqYCh3HLoO7GSIXBnHK18nIL4+hLLvso/Rml+J6AcpjOrpY5NBl2yT9meddgYKyk=,iv:xJtvlgYcJBpakmP8cSG4vAnuOgy1kB6B12LjMoAJGYM=,tag:n1xtZBwL05gJLhpFVsospg==,type:str]
  version: 3.13.2
---
apiVersion: v1
kind: Secret
metadata:
  name: platform-helper-mcp-credential
  namespace: kagent
type: Opaque
stringData:
  authorization: ENC[AES256_GCM,data:TTqd+/u8rs0kz3R7jCAP2EuvkNw0tAPWq73Zhp98coR8BItiA/ctZflupnLvCXCnSMbwDE4DhcRy1i0eJqaa7R4EGj+IeW4=,iv:y/mZHSdBMRd4nZZUXeeQ7gAaw8m8uybp+zfNmcJqZ50=,tag:wBqnoESSnVCi6ou9rkGnHg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByekVWZXhNa3NsbHplaWox
        TFBWN2xjQ25GZWM2RkVFbzcycGh5NDBPNzNNCkxZRUN6dTZSamp5WGpOR1gxbkpE
        ekRsdG9WRGs1Q3hGVitvTFVDNmNnWTQKLS0tIGlmdVNHQzBXQmZCK2JvSGtDVk14
        WHNCQVRBNG1zQkYvVHRZOG9JR3kzUDQKcUttgfuSy0r5bOJQ1s3wNbg6QivbnYSF
        VusuitZN+BKMI9UhmyBkrY+SQrqh8A0E778TFpXZ5nsffPiaJCrMhg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1nhwmnjct2c7jjes9f7qw45rphzjdvp2meluzzpm3myltaueahg2stefk6e
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-11T13:41:56Z"
  mac: ENC[AES256_GCM,data:7xs9MeCYVBtpHrdVCbpgt7izMJR8k0nSDxGfCM9HH+xlfidntPQ5liDcBSM17q2jfcEni60UBcJRjSzUoupiegM4uI/ZsauUMEsnzX+iZlBjqYCh3HLoO7GSIXBnHK18nIL4+hLLvso/Rml+J6AcpjOrpY5NBl2yT9meddgYKyk=,iv:xJtvlgYcJBpakmP8cSG4vAnuOgy1kB6B12LjMoAJGYM=,tag:n1xtZBwL05gJLhpFVsospg==,type:str]
  version: 3.13.2
