apiVersion: v1
kind: Secret
metadata:
  name: pg-synapse
  namespace: postgres
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:FR1RTODdLQ==,iv:zsef7tI8NuK7WiPG8to6bcoy/SgO8EgkoyLyceotbkU=,tag:3YuLCARzDpTt5vB1mOT7ng==,type:str]
  password: ENC[AES256_GCM,data:L+NB2e3Joi5X+LUZvNF1cPccwMsUIi1bBbAD8JhQnABIdL3e+P1fnUy/OFaxCVCB,iv:9GKnulgaorVQB00wrR0wmPVJ3k8u4tNxVUlzN2axwD4=,tag:7Kw21UuEOH2oIxVhtHxNtg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBma0FYQnF4bEdTdU1DNWxa
        UXR3a3kyYVBQcE1iNmtVUS95NlVkNlB2NWdNCmswakcwNW91UXBxODVuYlg3YzJD
        WVZFV1AzS2ZsTlpPcW5LMmNzVFRTaTgKLS0tIGd5RjFUaUdJa0NaejdGWGVva2hP
        M2hPdGg2aFAzZE1mcXdIV1JmVmlhVE0KFJZ9b+o6ympwsBJZ5j001TbCeINXXYk+
        e8o5pf3yuhHYNQ73pczy+NpLSQafG2yafC5Evs9NQokJozdW//92SA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1nhwmnjct2c7jjes9f7qw45rphzjdvp2meluzzpm3myltaueahg2stefk6e
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-10T12:51:06Z"
  mac: ENC[AES256_GCM,data:Z/UDEv7AZpopYQFN1pKiu0Tbp4Imzr2pEzCk26K0LZrfwG7QVVtOEtmJr1X9qBuY3IuDhULzqCfP+BN6A5374WzvW0ebpAcIx2YQ2hLs4XzyBhG7jCz45XZNjrQNiM6YqIOgUGBsUczGmiLpWYarwWFDN8vv+pHtMSxxMIsZnBo=,iv:0qiV4gAyHnVji+Yarxgsn09Bi8qp+Q4j3hBCjkcnI1Y=,tag:UhtiutaNqPTcMAqqW8kSjw==,type:str]
  version: 3.13.2
---
apiVersion: v1
kind: Secret
metadata:
  name: pg-mas
  namespace: postgres
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:XSSw,iv:B4Y8twDcGuAz/mUK0F3tqT/d6yBY+XScZ9gCXCmZcV0=,tag:vln5gK8uAg+iNq/zUY7LSQ==,type:str]
  password: ENC[AES256_GCM,data:NRG3CszFhQY3IbDdRKrqIYYQtROHcA+FxICnQ6QGg/qywuQZ0Ge0dj01k7YxqxWp,iv:idp3R2Zr6vSWST8NQ8eU6LEZmD0CFA5kIAv1l3Wt7W8=,tag:2n5lvzBMJQdECpewpy37mg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBma0FYQnF4bEdTdU1DNWxa
        UXR3a3kyYVBQcE1iNmtVUS95NlVkNlB2NWdNCmswakcwNW91UXBxODVuYlg3YzJD
        WVZFV1AzS2ZsTlpPcW5LMmNzVFRTaTgKLS0tIGd5RjFUaUdJa0NaejdGWGVva2hP
        M2hPdGg2aFAzZE1mcXdIV1JmVmlhVE0KFJZ9b+o6ympwsBJZ5j001TbCeINXXYk+
        e8o5pf3yuhHYNQ73pczy+NpLSQafG2yafC5Evs9NQokJozdW//92SA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1nhwmnjct2c7jjes9f7qw45rphzjdvp2meluzzpm3myltaueahg2stefk6e
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-10T12:51:06Z"
  mac: ENC[AES256_GCM,data:Z/UDEv7AZpopYQFN1pKiu0Tbp4Imzr2pEzCk26K0LZrfwG7QVVtOEtmJr1X9qBuY3IuDhULzqCfP+BN6A5374WzvW0ebpAcIx2YQ2hLs4XzyBhG7jCz45XZNjrQNiM6YqIOgUGBsUczGmiLpWYarwWFDN8vv+pHtMSxxMIsZnBo=,iv:0qiV4gAyHnVji+Yarxgsn09Bi8qp+Q4j3hBCjkcnI1Y=,tag:UhtiutaNqPTcMAqqW8kSjw==,type:str]
  version: 3.13.2
---
apiVersion: v1
kind: Secret
metadata:
  name: pg-bridge
  namespace: postgres
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:3MjWjwwS,iv:4zHjbtqqMfRJemrENlF6jAEHgxDMhs1OgyDJuSBwo90=,tag:Tmpjs76vPpKJqcfIqeJ9vw==,type:str]
  password: ENC[AES256_GCM,data:RRIFYcquyk+kVCbf5Umd/mWBKyCNj83R49xLauCy5QZjS0SCm2jzHIZPcKF9e3l4,iv:0/36CI9qkxp5DAr70rwZAfNLUctnRE59yjqChJyCLfM=,tag:93uDAkpp6wV8woE25Zwfng==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBma0FYQnF4bEdTdU1DNWxa
        UXR3a3kyYVBQcE1iNmtVUS95NlVkNlB2NWdNCmswakcwNW91UXBxODVuYlg3YzJD
        WVZFV1AzS2ZsTlpPcW5LMmNzVFRTaTgKLS0tIGd5RjFUaUdJa0NaejdGWGVva2hP
        M2hPdGg2aFAzZE1mcXdIV1JmVmlhVE0KFJZ9b+o6ympwsBJZ5j001TbCeINXXYk+
        e8o5pf3yuhHYNQ73pczy+NpLSQafG2yafC5Evs9NQokJozdW//92SA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1nhwmnjct2c7jjes9f7qw45rphzjdvp2meluzzpm3myltaueahg2stefk6e
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-10T12:51:06Z"
  mac: ENC[AES256_GCM,data:Z/UDEv7AZpopYQFN1pKiu0Tbp4Imzr2pEzCk26K0LZrfwG7QVVtOEtmJr1X9qBuY3IuDhULzqCfP+BN6A5374WzvW0ebpAcIx2YQ2hLs4XzyBhG7jCz45XZNjrQNiM6YqIOgUGBsUczGmiLpWYarwWFDN8vv+pHtMSxxMIsZnBo=,iv:0qiV4gAyHnVji+Yarxgsn09Bi8qp+Q4j3hBCjkcnI1Y=,tag:UhtiutaNqPTcMAqqW8kSjw==,type:str]
  version: 3.13.2
---
apiVersion: v1
kind: Secret
metadata:
  name: pg-kagent
  namespace: postgres
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:UkrrDFAg,iv:JlHsWf44kr8+JHLPKRx9qHxr7Tw3ZFXHP7p74VtHIpk=,tag:cb1Evh13WcnPf5OadH4OhA==,type:str]
  password: ENC[AES256_GCM,data:YiP2UDMwolHzyonoLDwhNRw11zS+0/5wVfHshikhZ/3IEh3h2ipj9D5BE9UCTJiz,iv:2EYswgZQV++NNR8oB7k2qTQ3RNO5+k+BeWIUKSmWMGE=,tag:sDso5RrR77nPwkEFP2lzJw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBma0FYQnF4bEdTdU1DNWxa
        UXR3a3kyYVBQcE1iNmtVUS95NlVkNlB2NWdNCmswakcwNW91UXBxODVuYlg3YzJD
        WVZFV1AzS2ZsTlpPcW5LMmNzVFRTaTgKLS0tIGd5RjFUaUdJa0NaejdGWGVva2hP
        M2hPdGg2aFAzZE1mcXdIV1JmVmlhVE0KFJZ9b+o6ympwsBJZ5j001TbCeINXXYk+
        e8o5pf3yuhHYNQ73pczy+NpLSQafG2yafC5Evs9NQokJozdW//92SA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1nhwmnjct2c7jjes9f7qw45rphzjdvp2meluzzpm3myltaueahg2stefk6e
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-10T12:51:06Z"
  mac: ENC[AES256_GCM,data:Z/UDEv7AZpopYQFN1pKiu0Tbp4Imzr2pEzCk26K0LZrfwG7QVVtOEtmJr1X9qBuY3IuDhULzqCfP+BN6A5374WzvW0ebpAcIx2YQ2hLs4XzyBhG7jCz45XZNjrQNiM6YqIOgUGBsUczGmiLpWYarwWFDN8vv+pHtMSxxMIsZnBo=,iv:0qiV4gAyHnVji+Yarxgsn09Bi8qp+Q4j3hBCjkcnI1Y=,tag:UhtiutaNqPTcMAqqW8kSjw==,type:str]
  version: 3.13.2
