apiVersion: v1
kind: Secret
metadata:
    name: pg-synapse
    namespace: postgres
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:xjZSxxfXRw==,iv:bMoYMgRhvlByh+QO2PaXNMjNTBAzH5HgmSiYKS1MNq8=,tag:JDh21vPXRf70YSNJ7DtH4A==,type:str]
    password: ENC[AES256_GCM,data:xTu7MIftK9K1o47HdcFq40dcbwwBTwImPYcc8xvMYmPe61PCm322cb+MWyNnvmFj,iv:uNPc3YzYnawMLq3VlwnF1GySNW8bdUwsmgPssvp0xjg=,tag:finD8Jbcv0+ic8apK8iuvQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuMTNpUTNpM3V1SlBBOU8x
            UDZSR1hZM0JCSms1citkTDlzN1JzNmxBMVRFCkp1dzZLNHBWSmxTQlBKeXJHNVZX
            OUJUM05obTd2bUpXSGFyenAyWWdFcUkKLS0tIExyajNEMzNBSjh4L3dSeDhjRXdN
            dzJoZ2FBdXZhN0Z0eDBOSEVsL0VpbkkK6hl5OsSKVoiPidTZtgx/kHydqrilJZvS
            /E2uS7kM403UO74DrIeu+GPO0nrR84TW+WAt5w2fSdveSW6bS7h62g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhwmnjct2c7jjes9f7qw45rphzjdvp2meluzzpm3myltaueahg2stefk6e
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-10T14:12:09Z"
    mac: ENC[AES256_GCM,data:DcBarbsC4B0X+OlR54chE9sRI92l1+OkYLfjE9vcbeKZHF1YDvJWEschO4rEBKFftQCB3oi+HpIRYFFI4f/O7jK+QzEIMCqJmN8wjI4EbYqhzqBObYTr9xEKsql2V74IpaSpll7KMXX3NSGEaKVD/bj/QS37l29+IgsDehd/pi8=,iv:hKdyyhEyIrF0CUhVycjKF0836oMNkLR1J+PX2woquNw=,tag:niKQZgAxUrvkiZQl3TCWdA==,type:str]
    version: 3.13.2
---
apiVersion: v1
kind: Secret
metadata:
    name: pg-mas
    namespace: postgres
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:vw6w,iv:l1brYA8alVgI4nJmEfVLlpIFBFJ3tkLiK3l4Ctp58So=,tag:Aw9Dka7H+V0TWc0ZHxG3Rg==,type:str]
    password: ENC[AES256_GCM,data:6F4VWeOCv7xSNCcEA7fVTRkD/AZ+xq9NR+jYU8xstEVSE1CwScxu9w5UyppeewFh,iv:SIjmiUUckqZF8C2UD/a+nmkA34nj2WyNDZoC1Ee/ccU=,tag:kRJnmQbe+LJ2ksleBLhitQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuMTNpUTNpM3V1SlBBOU8x
            UDZSR1hZM0JCSms1citkTDlzN1JzNmxBMVRFCkp1dzZLNHBWSmxTQlBKeXJHNVZX
            OUJUM05obTd2bUpXSGFyenAyWWdFcUkKLS0tIExyajNEMzNBSjh4L3dSeDhjRXdN
            dzJoZ2FBdXZhN0Z0eDBOSEVsL0VpbkkK6hl5OsSKVoiPidTZtgx/kHydqrilJZvS
            /E2uS7kM403UO74DrIeu+GPO0nrR84TW+WAt5w2fSdveSW6bS7h62g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhwmnjct2c7jjes9f7qw45rphzjdvp2meluzzpm3myltaueahg2stefk6e
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-10T14:12:09Z"
    mac: ENC[AES256_GCM,data:DcBarbsC4B0X+OlR54chE9sRI92l1+OkYLfjE9vcbeKZHF1YDvJWEschO4rEBKFftQCB3oi+HpIRYFFI4f/O7jK+QzEIMCqJmN8wjI4EbYqhzqBObYTr9xEKsql2V74IpaSpll7KMXX3NSGEaKVD/bj/QS37l29+IgsDehd/pi8=,iv:hKdyyhEyIrF0CUhVycjKF0836oMNkLR1J+PX2woquNw=,tag:niKQZgAxUrvkiZQl3TCWdA==,type:str]
    version: 3.13.2
---
apiVersion: v1
kind: Secret
metadata:
    name: pg-bridge
    namespace: postgres
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:O8/3xCPd,iv:IWv8f12zR1nO4v0AHwK/tYIQA1ssP1MHwgxyzoDIX6Y=,tag:VIDyysGzV6o/PsdM9gMdMw==,type:str]
    password: ENC[AES256_GCM,data:ey2HyTyuwF0IekuQLoZVD8X6JPrsHejwtauyID7DY4OwfWrwsUBkEPa4p8XcJAWL,iv:M/T4qPcCEsun/oi8hqxcOV6OKxguVaieXox04WTXzJg=,tag:wBwYKupm3uk/ej5m3qbgDw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuMTNpUTNpM3V1SlBBOU8x
            UDZSR1hZM0JCSms1citkTDlzN1JzNmxBMVRFCkp1dzZLNHBWSmxTQlBKeXJHNVZX
            OUJUM05obTd2bUpXSGFyenAyWWdFcUkKLS0tIExyajNEMzNBSjh4L3dSeDhjRXdN
            dzJoZ2FBdXZhN0Z0eDBOSEVsL0VpbkkK6hl5OsSKVoiPidTZtgx/kHydqrilJZvS
            /E2uS7kM403UO74DrIeu+GPO0nrR84TW+WAt5w2fSdveSW6bS7h62g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhwmnjct2c7jjes9f7qw45rphzjdvp2meluzzpm3myltaueahg2stefk6e
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-10T14:12:09Z"
    mac: ENC[AES256_GCM,data:DcBarbsC4B0X+OlR54chE9sRI92l1+OkYLfjE9vcbeKZHF1YDvJWEschO4rEBKFftQCB3oi+HpIRYFFI4f/O7jK+QzEIMCqJmN8wjI4EbYqhzqBObYTr9xEKsql2V74IpaSpll7KMXX3NSGEaKVD/bj/QS37l29+IgsDehd/pi8=,iv:hKdyyhEyIrF0CUhVycjKF0836oMNkLR1J+PX2woquNw=,tag:niKQZgAxUrvkiZQl3TCWdA==,type:str]
    version: 3.13.2
---
apiVersion: v1
kind: Secret
metadata:
    name: pg-kagent
    namespace: postgres
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:J5wsO55J,iv:dWmgqm9KHPX/ACc9V/LplZHwKReST03FbxhRi+ikbXY=,tag:uaz9X4xU/XO4Se6FZOUsIw==,type:str]
    password: ENC[AES256_GCM,data:dBO21agOrwbH8zgSvcpCahDFIswH4yaqyAGsx9KVK07g7VRjJepQtB1WGQw1mXCT,iv:7Ge6mBL01jihWzs8uKhdTxf70dBoN36l5rEpFnjkbmo=,tag:LeXFbZrBRXsjmVopDQcQbA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuMTNpUTNpM3V1SlBBOU8x
            UDZSR1hZM0JCSms1citkTDlzN1JzNmxBMVRFCkp1dzZLNHBWSmxTQlBKeXJHNVZX
            OUJUM05obTd2bUpXSGFyenAyWWdFcUkKLS0tIExyajNEMzNBSjh4L3dSeDhjRXdN
            dzJoZ2FBdXZhN0Z0eDBOSEVsL0VpbkkK6hl5OsSKVoiPidTZtgx/kHydqrilJZvS
            /E2uS7kM403UO74DrIeu+GPO0nrR84TW+WAt5w2fSdveSW6bS7h62g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhwmnjct2c7jjes9f7qw45rphzjdvp2meluzzpm3myltaueahg2stefk6e
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-10T14:12:09Z"
    mac: ENC[AES256_GCM,data:DcBarbsC4B0X+OlR54chE9sRI92l1+OkYLfjE9vcbeKZHF1YDvJWEschO4rEBKFftQCB3oi+HpIRYFFI4f/O7jK+QzEIMCqJmN8wjI4EbYqhzqBObYTr9xEKsql2V74IpaSpll7KMXX3NSGEaKVD/bj/QS37l29+IgsDehd/pi8=,iv:hKdyyhEyIrF0CUhVycjKF0836oMNkLR1J+PX2woquNw=,tag:niKQZgAxUrvkiZQl3TCWdA==,type:str]
    version: 3.13.2
---
apiVersion: v1
kind: Secret
metadata:
    name: pg-synapse
    namespace: matrix
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:tQLj4XPirQ==,iv:MBY02rtGtLgddI5Vo4kaNfYSRbXPicJQvnbQLbGxOaw=,tag:wMu+/R2k/cyt8XPmqc/H9Q==,type:str]
    password: ENC[AES256_GCM,data:iySVayNNSa1M+GL/PSRVbA6TjVI5T7OONad5wpPivfdyBVVz+ZvBPi3Z4Om42tyj,iv:+joaq0KCsOwPDKTg+2NVw6eqPPVS7ETeOADk+sNTyEM=,tag:ukFCOrmsdW4Ap0OST5q4WA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuMTNpUTNpM3V1SlBBOU8x
            UDZSR1hZM0JCSms1citkTDlzN1JzNmxBMVRFCkp1dzZLNHBWSmxTQlBKeXJHNVZX
            OUJUM05obTd2bUpXSGFyenAyWWdFcUkKLS0tIExyajNEMzNBSjh4L3dSeDhjRXdN
            dzJoZ2FBdXZhN0Z0eDBOSEVsL0VpbkkK6hl5OsSKVoiPidTZtgx/kHydqrilJZvS
            /E2uS7kM403UO74DrIeu+GPO0nrR84TW+WAt5w2fSdveSW6bS7h62g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhwmnjct2c7jjes9f7qw45rphzjdvp2meluzzpm3myltaueahg2stefk6e
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-10T14:12:09Z"
    mac: ENC[AES256_GCM,data:DcBarbsC4B0X+OlR54chE9sRI92l1+OkYLfjE9vcbeKZHF1YDvJWEschO4rEBKFftQCB3oi+HpIRYFFI4f/O7jK+QzEIMCqJmN8wjI4EbYqhzqBObYTr9xEKsql2V74IpaSpll7KMXX3NSGEaKVD/bj/QS37l29+IgsDehd/pi8=,iv:hKdyyhEyIrF0CUhVycjKF0836oMNkLR1J+PX2woquNw=,tag:niKQZgAxUrvkiZQl3TCWdA==,type:str]
    version: 3.13.2
---
apiVersion: v1
kind: Secret
metadata:
    name: pg-mas
    namespace: matrix
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:1fsC,iv:wWAZzwaoxPG/7XilSCGFCF22ngKUccBTGEVPecVkfBU=,tag:hedmD/5sxacZu3283xq10A==,type:str]
    password: ENC[AES256_GCM,data:74S/3KBXnBrG53jtQXxAPcVZCm0fp57h1NbgKyZcXpG9LGokT5OtzIATUd6eHsR8,iv:/P59Pi+s5i8TQAh2bSBEWHujuSUFOAmyXS7wZcikCkQ=,tag:wKpFLVQnPdQXA58urvTnGA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuMTNpUTNpM3V1SlBBOU8x
            UDZSR1hZM0JCSms1citkTDlzN1JzNmxBMVRFCkp1dzZLNHBWSmxTQlBKeXJHNVZX
            OUJUM05obTd2bUpXSGFyenAyWWdFcUkKLS0tIExyajNEMzNBSjh4L3dSeDhjRXdN
            dzJoZ2FBdXZhN0Z0eDBOSEVsL0VpbkkK6hl5OsSKVoiPidTZtgx/kHydqrilJZvS
            /E2uS7kM403UO74DrIeu+GPO0nrR84TW+WAt5w2fSdveSW6bS7h62g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhwmnjct2c7jjes9f7qw45rphzjdvp2meluzzpm3myltaueahg2stefk6e
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-10T14:12:09Z"
    mac: ENC[AES256_GCM,data:DcBarbsC4B0X+OlR54chE9sRI92l1+OkYLfjE9vcbeKZHF1YDvJWEschO4rEBKFftQCB3oi+HpIRYFFI4f/O7jK+QzEIMCqJmN8wjI4EbYqhzqBObYTr9xEKsql2V74IpaSpll7KMXX3NSGEaKVD/bj/QS37l29+IgsDehd/pi8=,iv:hKdyyhEyIrF0CUhVycjKF0836oMNkLR1J+PX2woquNw=,tag:niKQZgAxUrvkiZQl3TCWdA==,type:str]
    version: 3.13.2
