apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayBackend
metadata:
  name: llm-demo
  namespace: agentgateway-system
  annotations:
    fgentic.dev/model-admission: >-
      request.method == "GET" || (request.method == "POST" && "x-fgentic-data-classification" in request.headers && ("${llm_model}" == "fgentic-demo" && request.headers["x-fgentic-data-classification"] in ["public"]))
spec:
  ai:
    provider:
      openai:
        model: ${llm_model}
      host: demo-llm.models.svc.cluster.local
      port: 80
