{{- if .Values.metrics.podMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "activitypub-agent-gateway.fullname" . }}
  labels:
    {{- include "activitypub-agent-gateway.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "activitypub-agent-gateway.selectorLabels" . | nindent 6 }}
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      interval: 30s
{{- end }}
