apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mautrix-bridge.fullname" . }}
  labels:
    {{- include "mautrix-bridge.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- required "config.content is required" .Values.config.content | nindent 4 }}
