apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-budget
  namespace: activitypub
spec:
  hard:
    pods: "${quota_small_pods}"
    requests.cpu: "${quota_small_requests_cpu}"
    requests.memory: "${quota_small_requests_memory}"
    limits.cpu: "${quota_small_limits_cpu}"
    limits.memory: "${quota_small_limits_memory}"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: container-defaults
  namespace: activitypub
spec:
  limits:
    - type: Container
      default:
        cpu: "${quota_default_limit_cpu}"
        memory: "${quota_default_limit_memory}"
      defaultRequest:
        cpu: "${quota_default_request_cpu}"
        memory: "${quota_default_request_memory}"
