apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mautrix-slack
  namespace: flux-system
spec:
  interval: 30m
  retryInterval: 2m
  path: ./infra/bridges/slack
  prune: true
  wait: true
  timeout: 5m
  dependsOn:
    - name: platform-secrets
    - name: postgres
    - name: matrix
    - name: bridge
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: platform-settings
      - kind: ConfigMap
        name: platform-settings-overrides
        optional: true
