apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - resource-quotas.yaml
  - deployment.yaml
  - service.yaml
  - httproute.yaml
  - networkpolicy.yaml

configMapGenerator:
  - name: ketesa-config
    namespace: admin
    files:
      - config.json
