apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: kagent-controller
  namespace: kagent
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/instance: kagent
      app.kubernetes.io/name: kagent
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: kagent-kmcp-controller-manager
  namespace: kagent
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: kagent
      app.kubernetes.io/name: kmcp
      control-plane: controller-manager
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: kagent-tools
  namespace: kagent
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: kagent
      app.kubernetes.io/name: kagent-tools
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: kagent-ui
  namespace: kagent
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: ui
      app.kubernetes.io/instance: kagent
      app.kubernetes.io/name: kagent
