#!/usr/bin/env bash
# Render the time-bounded-trust review/expiry PrometheusRule from the partner trust registry (issue #463).
#
# For each admitted partner the registry's review_by and valid_until dates become content-free recording
# rules (a server_name label + a UTC epoch, no content, no secret); two alert rules warn when a review is
# due within the lead window and when access has expired. Rendering from the registry keeps the alert in
# lock-step with the signed validity window: renewal (a new signed window) re-renders new epochs.
#
# This is a production-federation artifact (a cluster that runs BOTH the observability stack and federated
# partners); it is an opt-in monitors Component, validated offline by promtool, not wired into a default
# cluster DAG. An expired valid_until also fails check:fed-registry closed — this alert is the live warning,
# never a silent traffic kill-switch (immediate containment is fed:break-glass, #350).
#
# Deterministic: re-rendering a clean tree is a no-op. `--out-root DIR` writes under DIR instead of the repo.
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
readonly ROOT_DIR
# shellcheck source=scripts/lib.sh
source "${ROOT_DIR}/scripts/lib.sh"

require_commands yq jq date

OUT_ROOT="${ROOT_DIR}"
# Review-due lead window (seconds); default 14 days. Configurable per deployment via this argument.
LEAD_SECONDS="1209600"
while [ "$#" -gt 0 ]; do
	case "$1" in
		--out-root)
			OUT_ROOT="${2:?"--out-root requires a directory"}"
			shift 2
			;;
		--lead-seconds)
			LEAD_SECONDS="${2:?"--lead-seconds requires a value"}"
			shift 2
			;;
		*) fail "unknown argument: $1" ;;
	esac
done
readonly OUT_ROOT LEAD_SECONDS

readonly REGISTRY="${ROOT_DIR}/infra/federation/registry/partners.yaml"
REGISTRY_JSON="$(yq -o=json '.' "${REGISTRY}")"
readonly REGISTRY_JSON
readonly OUT_DIR="${OUT_ROOT}/infra/observability/monitors/components/federation-trust-review"
readonly RECORDING_FILE="${OUT_DIR}/recording-rules.yaml"
readonly ALERT_FILE="${OUT_DIR}/alert-rules.yaml"
mkdir -p "${OUT_DIR}"

# Emit the recording rules for each admitted partner that declares dates. review_by is required; valid_until
# is optional, so a partner without it gets only a review-by series.
recording_rules=""
admitted_partners="$(jq -r '.partners[] | select(.role == "admitted") | .server_name' <<<"${REGISTRY_JSON}")"
while IFS= read -r partner; do
	[ -n "${partner}" ] || continue
	review_by="$(jq -r --arg p "${partner}" '.partners[] | select(.server_name == $p) | .review_by' <<<"${REGISTRY_JSON}")"
	valid_until="$(jq -r --arg p "${partner}" '.partners[] | select(.server_name == $p) | .valid_until // ""' <<<"${REGISTRY_JSON}")"
	review_epoch="$(date -u -d "${review_by}" +%s)"
	recording_rules+="        - record: fgentic:federation_partner_review_by:timestamp
          expr: vector(${review_epoch})
          labels:
            server_name: ${partner}
"
	if [ -n "${valid_until}" ]; then
		valid_epoch="$(date -u -d "${valid_until}" +%s)"
		recording_rules+="        - record: fgentic:federation_partner_valid_until:timestamp
          expr: vector(${valid_epoch})
          labels:
            server_name: ${partner}
"
	fi
done <<<"${admitted_partners}"

# Recording rules (rendered from the registry): each admitted partner's review_by/valid_until as a
# content-free constant series. Split from the alerts so promtool can unit-test the alert logic with
# small synthetic timestamps instead of evaluating half a billion real-epoch intervals.
cat >"${RECORDING_FILE}" <<EOF
# GENERATED by scripts/fed-trust-alert-render.sh from infra/federation/registry/partners.yaml (issue #463).
# Do not hand-edit — run 'mise run fed:trust-alert-render'. Each admitted partner's review_by/valid_until
# is a content-free recording rule (server_name label + UTC epoch, no content, no secret). The alert
# rules live in alert-rules.yaml. Opt-in production-federation artifact validated by promtool.
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: federation-trust-timestamps
  namespace: monitoring
spec:
  groups:
    - name: federation-trust-timestamps
      rules:
${recording_rules%$'\n'}
EOF

# Alert rules (lead window rendered in): they consume the recording-rule series above. Kept separate so
# the promtool fixture can feed synthetic timestamps without colliding with the constant recording rules.
cat >"${ALERT_FILE}" <<EOF
# GENERATED by scripts/fed-trust-alert-render.sh (issue #463). Do not hand-edit — run
# 'mise run fed:trust-alert-render'. These alerts consume the recording rules in recording-rules.yaml.
# The review-due lead window is ${LEAD_SECONDS}s. An expired valid_until also fails check:fed-registry
# closed; this alert is the live warning, never a silent traffic kill-switch (containment is #350).
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: federation-trust-review
  namespace: monitoring
spec:
  groups:
    - name: federation-trust-review
      rules:
        - alert: FederationPartnerReviewDue
          # A partner's contracted control-review date is within the lead window or has passed. Renew by
          # re-signing the bilateral agreement with a new window (#353); this does not sever traffic.
          expr: (fgentic:federation_partner_review_by:timestamp - time()) < ${LEAD_SECONDS}
          labels:
            severity: warning
          annotations:
            summary: Federated partner control review is due
            description: >-
              The contracted control-review date for a federated partner is within the lead window or
              has passed. Re-review the partner's controls and renew the signed agreement with a new
              validity window, or offboard the partner.
        - alert: FederationPartnerAccessExpired
          # The partner's hard validity window has passed: federation trust config will not reconcile
          # (check:fed-registry fails closed). Renew or offboard; for immediate cutoff use fed:break-glass.
          expr: (fgentic:federation_partner_valid_until:timestamp - time()) < 0
          labels:
            severity: critical
          annotations:
            summary: Federated partner access has expired
            description: >-
              A federated partner's valid_until date has passed. Federation trust config will not
              reconcile until the partner is renewed (re-signed with a new window) or offboarded. This
              alert is the live warning; immediate containment is the break-glass path (#350).
EOF

echo "fed-trust-alert: rendered the review/expiry recording + alert rules from the partner trust registry"
