apiVersion: v1
kind: Secret
metadata:
    name: pg-knowledge-owner
    namespace: postgres
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:mkjX+fWgS+j+EnF6o09U,iv:6qWLAfkxKX1Kifj8iN7sBlOhkqSiUrNU91HcLPZydA0=,tag:/OpmMrj9ZkOY3e5iPMFczQ==,type:str]
    password: ENC[AES256_GCM,data:YOxRhY1umouUrLFQRCHPi00zUo4u738cBZIH05UeW3CAynorn4bQP3j2t7aw1Fw5,iv:+0bHX/df+bLKy4vYIkp48rZSfKxMRQnn+fHmPcCPtFs=,tag:D/5MpCpNOFo2SglqqtoTrA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBVHN2R0cyb1lGSkxBQ2o3
            d3c0aGRvVmpEYmpnT2l6djM2aGJZOUJKdUhzCmg2MTlsWDdSM1lGUUxITnNQSlBu
            WkdPcSt0UmoxRDRTTmZFdXdqaVlDTTgKLS0tIC9wQ3R4VDFYVlNrSFFwWWxmbURB
            WFczSWVaTjA3VkpkVVdObnBiYTYxeHcKuXowZWpwiB70CHENbkmOu3PiMh5QKJMW
            3qMW5AcWArfZhBSgQid4IQtXBwUCXoUxoC+HZaq6nrNDM5LjM1DFRw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhwmnjct2c7jjes9f7qw45rphzjdvp2meluzzpm3myltaueahg2stefk6e
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-15T17:04:47Z"
    mac: ENC[AES256_GCM,data:atBaUIId/63UjyIVQE4gl8EwXI01YXqbieG8kR2IVoboZ6SJJUnAiObA8OeZPMgNwdzVQ+16z2aC17iBu1MBeQTm0WL7Dj98XAVz0t8LQFcQvcwSq398Ia3/lkqvx/8JgtbHasCsJtTLixq07Px3nH+YoKYfX+LHyS6QA2c5NAc=,iv:SHLiOmkhBkhEG4kF04Mk4hpohPZ6tZzsrNHBe2o9Lao=,tag:Sk0qxiQfwTO6mhO7J+UbHQ==,type:str]
    version: 3.13.2
---
apiVersion: v1
kind: Secret
metadata:
    name: pg-knowledge-retrieval
    namespace: postgres
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:6sNu8YmgFdpMplVbH/j+yISH+g==,iv:Oiksoybe4/REJzmZe0F3DNeseM6puaKhVP1TyiUad2c=,tag:M6ENj0sVwWA5e1qnhcd9ow==,type:str]
    password: ENC[AES256_GCM,data:AdJ05soPrrOuxzXSo7KLwazLJm8PVEnwiWE2rgP2X2YOkO9DkLCgr0SFvnd9Yqcr,iv:fKvIhU5T9RNj62KXWy+tG6UGDbUzNoFt5JyBtGRdjr4=,tag:3xUW9JEsBeGPxmpptbkKLA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBVHN2R0cyb1lGSkxBQ2o3
            d3c0aGRvVmpEYmpnT2l6djM2aGJZOUJKdUhzCmg2MTlsWDdSM1lGUUxITnNQSlBu
            WkdPcSt0UmoxRDRTTmZFdXdqaVlDTTgKLS0tIC9wQ3R4VDFYVlNrSFFwWWxmbURB
            WFczSWVaTjA3VkpkVVdObnBiYTYxeHcKuXowZWpwiB70CHENbkmOu3PiMh5QKJMW
            3qMW5AcWArfZhBSgQid4IQtXBwUCXoUxoC+HZaq6nrNDM5LjM1DFRw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhwmnjct2c7jjes9f7qw45rphzjdvp2meluzzpm3myltaueahg2stefk6e
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-15T17:04:47Z"
    mac: ENC[AES256_GCM,data:atBaUIId/63UjyIVQE4gl8EwXI01YXqbieG8kR2IVoboZ6SJJUnAiObA8OeZPMgNwdzVQ+16z2aC17iBu1MBeQTm0WL7Dj98XAVz0t8LQFcQvcwSq398Ia3/lkqvx/8JgtbHasCsJtTLixq07Px3nH+YoKYfX+LHyS6QA2c5NAc=,iv:SHLiOmkhBkhEG4kF04Mk4hpohPZ6tZzsrNHBe2o9Lao=,tag:Sk0qxiQfwTO6mhO7J+UbHQ==,type:str]
    version: 3.13.2
---
apiVersion: v1
kind: Secret
metadata:
    name: pg-knowledge-retrieval
    namespace: knowledge
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:VY2oamPT2Y3DkxiJwhoxOrxgMw==,iv:uFNZolIwoea72M+GTF4IWwOC4UrwfUzEcNaNXk3FaL4=,tag:HkJFvEkwv1YMYvAKGnQv/Q==,type:str]
    password: ENC[AES256_GCM,data:+wd7B+BAzARdgG83GGbWKcfbdBA4wbW9c74trupSfNsEGDFmIkeV06+X0LGCd0Tv,iv:SEqvpgXq4BXBBYf8kGDaoWgs3OOVm+kJrWNClfO+LWc=,tag:FWLqmv93e1QGMJo0TJF1ow==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBVHN2R0cyb1lGSkxBQ2o3
            d3c0aGRvVmpEYmpnT2l6djM2aGJZOUJKdUhzCmg2MTlsWDdSM1lGUUxITnNQSlBu
            WkdPcSt0UmoxRDRTTmZFdXdqaVlDTTgKLS0tIC9wQ3R4VDFYVlNrSFFwWWxmbURB
            WFczSWVaTjA3VkpkVVdObnBiYTYxeHcKuXowZWpwiB70CHENbkmOu3PiMh5QKJMW
            3qMW5AcWArfZhBSgQid4IQtXBwUCXoUxoC+HZaq6nrNDM5LjM1DFRw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhwmnjct2c7jjes9f7qw45rphzjdvp2meluzzpm3myltaueahg2stefk6e
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-15T17:04:47Z"
    mac: ENC[AES256_GCM,data:atBaUIId/63UjyIVQE4gl8EwXI01YXqbieG8kR2IVoboZ6SJJUnAiObA8OeZPMgNwdzVQ+16z2aC17iBu1MBeQTm0WL7Dj98XAVz0t8LQFcQvcwSq398Ia3/lkqvx/8JgtbHasCsJtTLixq07Px3nH+YoKYfX+LHyS6QA2c5NAc=,iv:SHLiOmkhBkhEG4kF04Mk4hpohPZ6tZzsrNHBe2o9Lao=,tag:Sk0qxiQfwTO6mhO7J+UbHQ==,type:str]
    version: 3.13.2
